### PR TITLE
EdgeX Foundry Jakarta w/ Onvif Device Service + Edge Video Analytics

### LINKED ISSUE #9: Add Jakarta support to ORRA stack
Under demos, let's create a new folder named `OH-EXF-Jakarta` with support for deploying the Jakarta release of EdgeX Foundry in Open Horizon.  This will only use the specific services needed for a specific retail use case.  It will include support for an ONVIF device and DL Streamer service.

### PR DESCRIPTION
**Pull request by ajcasagrande**
See [README.md](https://github.com/ajcasagrande/orra/blob/edgex-jakarta/demos/OH-EXF-Jakarta/README.md) for info and how to

> Note: Device Onvif Service will not work until https://github.com/edgexfoundry-holding/device-onvif-camera/issues/56 is fixed

### CODE REVIEW

**Review by presatish — DISMISSED** [review]

**Comment by joewxboy** [comment]
@lenny-intel Are you able to review this?  I do not have write access, so my review won't allow us to merge this code.

**Comment by lenny-goodell** [comment]
> @lenny-intel Are you able to review this? I do not have write access, so my review won't allow us to merge this code.

No, I don't have committers rights . You should be able to since you are in this list: https://github.com/orgs/edgexfoundry-holding/teams/orra-committers/members

**Comment by joewxboy** [comment]
> > @lenny-intel Are you able to review this? I do not have write access, so my review won't allow us to merge this code.
> 
> No, I don't have committers rights . You should be able to since you are in this list: https://github.com/orgs/edgexfoundry-holding/teams/orra-committers/members

Thanks!  I don't know when that happened, but I appreciate it. :)

**Review by joewxboy — CHANGES_REQUESTED** [review]
Following the README instructions.
Set all of the env vars you mentioned.
I **also** needed to:

* export APP_BIND_HORIZON_DIR=/var/local/horizon
* export LOCAL_DOCKER_REGISTRY=joewxboy

AND I needed to manually remove the comment line from build/deploy-data.service.json

before I could run `make` successfully.

One last error I can't get past ... after make runs `git clone --depth=1 --branch v0.7.0 https://github.com/intel/edge-video-analytics-microservice.git src` I get the following error:

```
chmod +x src/tools/model_downloader/model_downloader.sh src/docker/run.sh
src/tools/model_downloader/model_downloader.sh --model-list models.list.yml
src/tools/model_downloader/model_downloader.sh: line 11: realpath: command not found
make[1]: *** [download-models] Error 127
make: *** [publish-model-data] Error 2
```

**Comment by ajcasagrande** [comment]
@joewxboy Thanks for the feedback. Here are my initial thoughts, but I will need to investigate further.

> export APP_BIND_HORIZON_DIR=/var/local/horizon

I removed this one from the README.md as I have added a default value in `defaults.mk` it seems like your machine is acting different than I expected, so I can always add it back to the README

> export LOCAL_DOCKER_REGISTRY=joewxboy

Are you saying you experienced the same issue as the `APP_BIND_HORIZON_DIR` var, where no defaults are present? Or that running using `make ... LOCAL_DOCKER_REGISTRY=<your-docker-registry-base>` did not work, or something else?

> AND I needed to manually remove the comment line from build/deploy-data.service.json

It sounds like the `sed` command I use to pre-process the json files is not working as intended on your machine. Possibly I am using a flag not supported on the Mac version. Does the `edgex-ui` service publish fine? It has a comment in it as well.

> One last error I can't get past ... after make runs git clone --depth=1 --branch v0.7.0 https://github.com/intel/edge-video-analytics-microservice.git src I get the following error:
> ```
> src/tools/model_downloader/model_downloader.sh: line 11: realpath: command not found
> ```

Yeah, `realpath` is not available by default on Mac. Unfortunately, I am utilizing a script from another repo to accomplish this, so I can't just patch it. I will need to investigate alternative approaches.

**Comment by joewxboy** [comment]
@ajcasagrande Thanks for the responses.  It sounds like many of the comments were due to my macOS environment.  If you intended this to only be run on Linux and/or a specific distro, please let me know.

Regarding the `export LOCAL_DOCKER_REGISTRY=joewxboy`, the defaults were expecting a repository on localhost port 4000 or something.

**Comment by ajcasagrande** [comment]
> @ajcasagrande Thanks for the responses. It sounds like many of the comments were due to my macOS environment. If you intended this to only be run on Linux and/or a specific distro, please let me know.

@joewxboy Mainly it has been tested on Ubuntu 18.04, but it should work fine on any linux distro.

> Regarding the `export LOCAL_DOCKER_REGISTRY=joewxboy`, the defaults were expecting a repository on localhost port 4000 or something.

Yeah I think the instructions around this can be improved a bit.

**Comment by ajcasagrande** [comment]
@joewxboy I pushed a commit that should let you get past the `realpath` issue.

**Comment by joewxboy** [comment]
> @joewxboy I pushed a commit that should let you get past the `realpath` issue.

Thanks.  Now I'm getting an error because it's attempting to update docker.io/edgexfoundry/device-onvif-camera and failing.  Not sure if it's due to my account, or appending edgexfoundry to the dockerhub path or both.

```
docker tag "edgexfoundry/device-onvif-camera:0.0.0-dev" "joewxboy/edgexfoundry/device-onvif-camera:0.0.0-dev"
pushing docker image...
docker push "joewxboy/edgexfoundry/device-onvif-camera:0.0.0-dev"
The push refers to repository [docker.io/joewxboy/edgexfoundry/device-onvif-camera]
593f60db9857: Preparing
90b21ce3c8b9: Preparing
0825ef6fc60b: Preparing
436f042635e8: Preparing
4fc242d58285: Preparing
denied: requested access to the resource is denied
make[1]: *** [push] Error 1
make: *** [publish-device-onvif-camera] Error 2
```

**Comment by ajcasagrande** [comment]
> Thanks. Now I'm getting an error because it's attempting to update docker.io/edgexfoundry/device-onvif-camera and failing. Not sure if it's due to my account, or appending edgexfoundry to the dockerhub path or both.
> 
> ```
> docker push "joewxboy/edgexfoundry/device-onvif-camera:0.0.0-dev"
> The push refers to repository [docker.io/joewxboy/edgexfoundry/device-onvif-camera]
> denied: requested access to the resource is denied
> ```

@joewxboy I think you need to login to your docker.io account. Try running [`docker login`](https://docs.docker.com/engine/reference/commandline/login/), and then run again.

**Comment by joewxboy** [comment]
> @joewxboy I think you need to login to your docker.io account. Try running [`docker login`](https://docs.docker.com/engine/reference/commandline/login/), and then run again.

I was logged in, but I ran the login command again and ran make again, and got the same error.

Note that the path is:

`joewxboy/edgexfoundry/device-onvif-camera:0.0.0-dev`

when I expected it to be:

`joewxboy/device-onvif-camera:0.0.0-dev`

**Comment by ajcasagrande** [comment]
Yeah I think there is some weirdness around how the image naming is handled since there are 3 different source of images:
1. Stock Docker Images
2. Stock EdgeX Images
3. Custom Built Images

Having said that,  I believe the `device-onvif-camera` is available as pre-built images now, so we can go ahead and replace the custom built code for that one at least.

Can you try and just run `make publish-deploy-data` and see what happens? And maybe `make publish-model-data`? Those are the two other images that are built locally.

**Comment by joewxboy** [comment]
> Can you try and just run `make publish-deploy-data` and see what happens? And maybe `make publish-model-data`? Those are the two other images that are built locally.

Yup, those two ran and completed with no issues. :)

**Comment by joewxboy** [comment]
Any new updates @ajcasagrande ?  What can we do to resolve and merge?

**Comment by ajcasagrande** [comment]
> Any new updates @ajcasagrande ? What can we do to resolve and merge?

My latest concern was that the device-onvif-camera images are built and pushed into the EdgeX nexus repositories and not docker hub yet, meaning it may need to be handled special. I haven't had the bandwidth to work on it, but I can take a look and see if there is a quick way to do it.

**Comment by ajcasagrande** [comment]
@joewxboy I setup the device-onvif-camera service to pull from the nexus registry for it's docker images. I am unable to test it at the moment. If you get a chance try it out and let me know.

**Comment by joewxboy** [comment]
> @joewxboy I setup the device-onvif-camera service to pull from the nexus registry for it's docker images. I am unable to test it at the moment. If you get a chance try it out and let me know.

I'm missing a variable:

```
Changing Horizon state to configured to register this node with Horizon...
Error setting node state to configured: Registration failed because variable DRIVER_DISCOVERYETHERNETINTERFACE for service examples/joewxboy.dev.device-onvif-camera is missing from mappings.. Please create an input file, define variables for service examples/joewxboy.dev.device-onvif-camera. Run 'hzn unregister' and then 'hzn register...' again with the -f flag to specify the input file.
Critical error encountered in registration. Attempting to undo registration steps to leave node in the unregistered state.
Waiting for Horizon node unregister to complete: Timeout in 885 seconds ...
Waiting for agent service to restart and checking the node configuration state...
Error: Registration failed. Node successfully returned to unregistered state.
make: *** [register] Error 99
```

Other than that, it's working much better now.

**Comment by ajcasagrande** [comment]
> I'm missing a variable

It appears that the hzn agent does not allow empty strings as the default value for a field. I guess we will need to provide an actual value there.

**Comment by ajcasagrande** [comment]
@joewxboy I have updated the device-onvif-camera service to the latest tag, and have provided a non-empty default value for `DRIVER_DISCOVERYETHERNETINTERFACE`. Ready for testing.

**Comment by joewxboy** [comment]
> @joewxboy I have updated the device-onvif-camera service to the latest tag, and have provided a non-empty default value for `DRIVER_DISCOVERYETHERNETINTERFACE`. Ready for testing.

Thanks.  Taking a look now.

**Comment by ajcasagrande** [comment]
@joewxboy I actually just noticed that we changed the naming convention for some variables in the latest code, so i updated the userInput to match.

**Review by joewxboy — APPROVED** [review]
After setting env vars per the README, running `make all` and then `make register` it appears to be working.

**Pull request merged**
