### PR TITLE
docs: add copyright headers and update readme

### LINKED ISSUE #15: Every file should have a copyright statement with an SPDX License identifier.

### PR DESCRIPTION
**Pull request by ajcasagrande**
Signed-off-by: Anthony Casagrande <anthony.j.casagrande@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- **N/A** Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## Issue Number:
Closes #15 

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by brianointel — DISMISSED** [review]

**Review by presatish — CHANGES_REQUESTED** [review]
Need to replace the camera-management app repo with the one from Edgex foundry examples.

**Comment by ajcasagrande** [comment]
> Need to replace the camera-management app repo with the one from Edgex foundry examples.

Fixed. Thanks.

**Review by presatish — APPROVED** [review]
LGTM.

**Review by presatish — APPROVED** [review]

**Review by joewxboy — APPROVED** [review]

**Comment by joewxboy** [comment]
Thank you for reviewing, @presatish

**Pull request merged**
